export const registros = {
    tecnologia: {
        abierto: [
            {
                id: 1,
                nombre: "Documento A",
                fechaEliminacion: "2024-12-01",
                eliminadoPor: "Juan Pérez",
                creadoPor: "María López",
                ubicacionOriginal: "Carpeta A",
            },
            {
                id: 2,
                nombre: "Documento B",
                fechaEliminacion: "2024-12-02",
                eliminadoPor: "Ana Martínez",
                creadoPor: "Carlos Ruiz",
                ubicacionOriginal: "Carpeta B",
            },
            {
                id: 3,
                nombre: "Documento C",
                fechaEliminacion: "2024-12-03",
                eliminadoPor: "Pedro García",
                creadoPor: "Luisa Fernández",
                ubicacionOriginal: "Carpeta C",
            },
            {
                id: 4,
                nombre: "Documento D",
                fechaEliminacion: "2024-12-04",
                eliminadoPor: "María Rodríguez",
                creadoPor: "José Sánchez",
                ubicacionOriginal: "Carpeta D",
            },
            {
                id: 5,
                nombre: "Documento E",
                fechaEliminacion: "2024-12-05",
                eliminadoPor: "Luis Torres",
                creadoPor: "Elena Gómez",
                ubicacionOriginal: "Carpeta E",
            },
            {
                id: 6,
                nombre: "Documento F",
                fechaEliminacion: "2024-12-06",
                eliminadoPor: "Sofía Díaz",
                creadoPor: "Miguel Hernández",
                ubicacionOriginal: "Carpeta F",
            },
            {
                id: 7,
                nombre: "Documento G",
                fechaEliminacion: "2024-12-07",
                eliminadoPor: "Diego Morales",
                creadoPor: "Laura Jiménez",
                ubicacionOriginal: "Carpeta G",
            },
            {
                id: 8,
                nombre: "Documento H",
                fechaEliminacion: "2024-12-08",
                eliminadoPor: "Carmen López",
                creadoPor: "David Ramírez",
                ubicacionOriginal: "Carpeta H",
            },
            {
                id: 9,
                nombre: "Documento I",
                fechaEliminacion: "2024-12-09",
                eliminadoPor: "Javier Navarro",
                creadoPor: "Isabel Castro",
                ubicacionOriginal: "Carpeta I",
            },
            {
                id: 10,
                nombre: "Documento J",
                fechaEliminacion: "2024-12-10",
                eliminadoPor: "Ana Ruiz",
                creadoPor: "Carlos Mendoza",
                ubicacionOriginal: "Carpeta J",
            },
            {
                id: 11,
                nombre: "Documento K",
                fechaEliminacion: "2024-12-11",
                eliminadoPor: "Roberto Fernández",
                creadoPor: "Marcela Ortiz",
                ubicacionOriginal: "Carpeta K",
            },
            {
                id: 12,
                nombre: "Documento L",
                fechaEliminacion: "2024-12-12",
                eliminadoPor: "Patricia García",
                creadoPor: "Sergio Vega",
                ubicacionOriginal: "Carpeta L",
            },
            {
                id: 13,
                nombre: "Documento M",
                fechaEliminacion: "2024-12-13",
                eliminadoPor: "Manuel Soto",
                creadoPor: "Lucía Rojas",
                ubicacionOriginal: "Carpeta M",
            },
            {
                id: 14,
                nombre: "Documento N",
                fechaEliminacion: "2024-12-14",
                eliminadoPor: "Ricardo Torres",
                creadoPor: "Andrea Núñez",
                ubicacionOriginal: "Carpeta N",
            },
            {
                id: 15,
                nombre: "Documento O",
                fechaEliminacion: "2024-12-15",
                eliminadoPor: "Claudia Martínez",
                creadoPor: "Eduardo Sánchez",
                ubicacionOriginal: "Carpeta O",
            },
            {
                id: 16,
                nombre: "Documento P",
                fechaEliminacion: "2024-12-16",
                eliminadoPor: "Lorena Castro",
                creadoPor: "Mario Pérez",
                ubicacionOriginal: "Carpeta P",
            },
            {
                id: 17,
                nombre: "Documento Q",
                fechaEliminacion: "2024-12-17",
                eliminadoPor: "Gabriel Moreno",
                creadoPor: "Paula Gómez",
                ubicacionOriginal: "Carpeta Q",
            },
            {
                id: 18,
                nombre: "Documento R",
                fechaEliminacion: "2024-12-18",
                eliminadoPor: "Fernando López",
                creadoPor: "Mariana Díaz",
                ubicacionOriginal: "Carpeta R",
            },
            {
                id: 19,
                nombre: "Documento S",
                fechaEliminacion: "2024-12-19",
                eliminadoPor: "Natalia Rodríguez",
                creadoPor: "Héctor Martínez",
                ubicacionOriginal: "Carpeta S",
            },
            {
                id: 20,
                nombre: "Documento T",
                fechaEliminacion: "2024-12-20",
                eliminadoPor: "Antonio Ruiz",
                creadoPor: "Carolina Fernández",
                ubicacionOriginal: "Carpeta T",
            },
            {
                id: 21,
                nombre: "Documento U",
                fechaEliminacion: "2024-12-21",
                eliminadoPor: "Marta Navarro",
                creadoPor: "Adrián Vega",
                ubicacionOriginal: "Carpeta U",
            },
            {
                id: 22,
                nombre: "Documento V",
                fechaEliminacion: "2024-12-22",
                eliminadoPor: "Diego Vargas",
                creadoPor: "Silvia Morales",
                ubicacionOriginal: "Carpeta V",
            },
            {
                id: 23,
                nombre: "Documento W",
                fechaEliminacion: "2024-12-23",
                eliminadoPor: "Esteban Castillo",
                creadoPor: "Clara Jiménez",
                ubicacionOriginal: "Carpeta W",
            },
            {
                id: 24,
                nombre: "Documento X",
                fechaEliminacion: "2024-12-24",
                eliminadoPor: "Santiago Rojas",
                creadoPor: "Valeria Mendoza",
                ubicacionOriginal: "Carpeta X",
            },
            {
                id: 25,
                nombre: "Documento Y",
                fechaEliminacion: "2024-12-25",
                eliminadoPor: "Ángela Soto",
                creadoPor: "Jorge García",
                ubicacionOriginal: "Carpeta Y",
            },
            {
                id: 26,
                nombre: "Documento Z",
                fechaEliminacion: "2024-12-26",
                eliminadoPor: "Francisco Torres",
                creadoPor: "Luisa Hernández",
                ubicacionOriginal: "Carpeta Z",
            },
            {
                id: 27,
                nombre: "Documento AA",
                fechaEliminacion: "2024-12-27",
                eliminadoPor: "Alicia Díaz",
                creadoPor: "Ignacio Ramírez",
                ubicacionOriginal: "Carpeta AA",
            },
            {
                id: 28,
                nombre: "Documento AB",
                fechaEliminacion: "2024-12-28",
                eliminadoPor: "Sebastián Gómez",
                creadoPor: "Laura Martínez",
                ubicacionOriginal: "Carpeta AB",
            },
            {
                id: 29,
                nombre: "Documento AC",
                fechaEliminacion: "2024-12-29",
                eliminadoPor: "Andrea Fernández",
                creadoPor: "Luis Moreno",
                ubicacionOriginal: "Carpeta AC",
            },
            {
                id: 30,
                nombre: "Documento AD",
                fechaEliminacion: "2024-12-30",
                eliminadoPor: "Claudio Ramírez",
                creadoPor: "Camila Ortega",
                ubicacionOriginal: "Carpeta AD",
            },

        ],
        notificado: [
            {
                id: 1,
                nombre: "Documento A",
                fechaEliminacion: "2024-12-01",
                eliminadoPor: "Juan Pérez",
                creadoPor: "María López",
                ubicacionOriginal: "Carpeta A",
            },
            {
                id: 2,
                nombre: "Documento B",
                fechaEliminacion: "2024-12-02",
                eliminadoPor: "Ana Martínez",
                creadoPor: "Carlos Ruiz",
                ubicacionOriginal: "Carpeta B",
            },
            {
                id: 3,
                nombre: "Documento C",
                fechaEliminacion: "2024-12-03",
                eliminadoPor: "Pedro García",
                creadoPor: "Luisa Fernández",
                ubicacionOriginal: "Carpeta C",
            },
            {
                id: 4,
                nombre: "Documento D",
                fechaEliminacion: "2024-12-04",
                eliminadoPor: "María Rodríguez",
                creadoPor: "José Sánchez",
                ubicacionOriginal: "Carpeta D",
            },
            {
                id: 5,
                nombre: "Documento E",
                fechaEliminacion: "2024-12-05",
                eliminadoPor: "Luis Torres",
                creadoPor: "Elena Gómez",
                ubicacionOriginal: "Carpeta E",
            },
            {
                id: 6,
                nombre: "Documento F",
                fechaEliminacion: "2024-12-06",
                eliminadoPor: "Sofía Díaz",
                creadoPor: "Miguel Hernández",
                ubicacionOriginal: "Carpeta F",
            },
            {
                id: 7,
                nombre: "Documento G",
                fechaEliminacion: "2024-12-07",
                eliminadoPor: "Diego Morales",
                creadoPor: "Laura Jiménez",
                ubicacionOriginal: "Carpeta G",
            },
            {
                id: 8,
                nombre: "Documento H",
                fechaEliminacion: "2024-12-08",
                eliminadoPor: "Carmen López",
                creadoPor: "David Ramírez",
                ubicacionOriginal: "Carpeta H",
            },
            {
                id: 9,
                nombre: "Documento I",
                fechaEliminacion: "2024-12-09",
                eliminadoPor: "Javier Navarro",
                creadoPor: "Isabel Castro",
                ubicacionOriginal: "Carpeta I",
            },
            {
                id: 10,
                nombre: "Documento J",
                fechaEliminacion: "2024-12-10",
                eliminadoPor: "Ana Ruiz",
                creadoPor: "Carlos Mendoza",
                ubicacionOriginal: "Carpeta J",
            },
            {
                id: 11,
                nombre: "Documento K",
                fechaEliminacion: "2024-12-11",
                eliminadoPor: "Roberto Fernández",
                creadoPor: "Marcela Ortiz",
                ubicacionOriginal: "Carpeta K",
            },
            {
                id: 12,
                nombre: "Documento L",
                fechaEliminacion: "2024-12-12",
                eliminadoPor: "Patricia García",
                creadoPor: "Sergio Vega",
                ubicacionOriginal: "Carpeta L",
            },
            {
                id: 13,
                nombre: "Documento M",
                fechaEliminacion: "2024-12-13",
                eliminadoPor: "Manuel Soto",
                creadoPor: "Lucía Rojas",
                ubicacionOriginal: "Carpeta M",
            },
            {
                id: 14,
                nombre: "Documento N",
                fechaEliminacion: "2024-12-14",
                eliminadoPor: "Ricardo Torres",
                creadoPor: "Andrea Núñez",
                ubicacionOriginal: "Carpeta N",
            },
            {
                id: 15,
                nombre: "Documento O",
                fechaEliminacion: "2024-12-15",
                eliminadoPor: "Claudia Martínez",
                creadoPor: "Eduardo Sánchez",
                ubicacionOriginal: "Carpeta O",
            },
            {
                id: 16,
                nombre: "Documento P",
                fechaEliminacion: "2024-12-16",
                eliminadoPor: "Fernando Díaz",
                creadoPor: "Susana García",
                ubicacionOriginal: "Carpeta P",
            },
            {
                id: 17,
                nombre: "Documento Q",
                fechaEliminacion: "2024-12-17",
                eliminadoPor: "Mónica López",
                creadoPor: "Alejandro Ruiz",
                ubicacionOriginal: "Carpeta Q",
            },
            {
                id: 18,
                nombre: "Documento R",
                fechaEliminacion: "2024-12-18",
                eliminadoPor: "Raúl Hernández",
                creadoPor: "Julia Castro",
                ubicacionOriginal: "Carpeta R",
            },
            {
                id: 19,
                nombre: "Documento S",
                fechaEliminacion: "2024-12-19",
                eliminadoPor: "Elena Morales",
                creadoPor: "Pablo Navarro",
                ubicacionOriginal: "Carpeta S",
            },
            {
                id: 20,
                nombre: "Documento T",
                fechaEliminacion: "2024-12-20",
                eliminadoPor: "Alberto Ramírez",
                creadoPor: "Carolina Mendoza",
                ubicacionOriginal: "Carpeta T",
            }
        ],
        descartado: [
            {
                id: 21,
                nombre: "Documento U",
                fechaEliminacion: "2024-12-21",
                eliminadoPor: "Rosa Ortiz",
                creadoPor: "Miguel Vega",
                ubicacionOriginal: "Carpeta U",
            },
            {
                id: 22,
                nombre: "Documento V",
                fechaEliminacion: "2024-12-22",
                eliminadoPor: "Daniel Soto",
                creadoPor: "Laura Rojas",
                ubicacionOriginal: "Carpeta V",
            },
            {
                id: 23,
                nombre: "Documento W",
                fechaEliminacion: "2024-12-23",
                eliminadoPor: "Sandra Núñez",
                creadoPor: "Ricardo Torres",
                ubicacionOriginal: "Carpeta W",
            },
            {
                id: 24,
                nombre: "Documento X",
                fechaEliminacion: "2024-12-24",
                eliminadoPor: "Gustavo Fernández",
                creadoPor: "María Sánchez",
                ubicacionOriginal: "Carpeta X",
            },
            {
                id: 25,
                nombre: "Documento Y",
                fechaEliminacion: "2024-12-25",
                eliminadoPor: "Beatriz García",
                creadoPor: "Jorge Díaz",
                ubicacionOriginal: "Carpeta Y",
            }
        ],
        rescatado: [
            {
                id: 26,
                nombre: "Documento Z",
                fechaEliminacion: "2024-12-26",
                eliminadoPor: "Pedro Martínez",
                creadoPor: "Ana López",
                ubicacionOriginal: "Carpeta Z",
            },
            {
                id: 27,
                nombre: "Documento AA",
                fechaEliminacion: "2024-12-27",
                eliminadoPor: "Luisa Ruiz",
                creadoPor: "Carlos Hernández",
                ubicacionOriginal: "Carpeta AA",
            },
            {
                id: 28,
                nombre: "Documento AB",
                fechaEliminacion: "2024-12-28",
                eliminadoPor: "José Morales",
                creadoPor: "Elena Castro",
                ubicacionOriginal: "Carpeta AB",
            },
            {
                id: 29,
                nombre: "Documento AC",
                fechaEliminacion: "2024-12-29",
                eliminadoPor: "Isabel Soto",
                creadoPor: "Sergio Navarro",
                ubicacionOriginal: "Carpeta AC",
            },
            {
                id: 30,
                nombre: "Documento AD",
                fechaEliminacion: "2024-12-30",
                eliminadoPor: "Miguel Ramírez",
                creadoPor: "Patricia Mendoza",
                ubicacionOriginal: "Carpeta AD",
            }
        ]
    },
    contabilidad: {
        abierto: [
            {
                id: 31,
                nombre: "Documento AE",
                fechaEliminacion: "2025-01-01",
                eliminadoPor: "Javier Ortiz",
                creadoPor: "Lucía Vega",
                ubicacionOriginal: "Carpeta AE",
            },
            {
                id: 32,
                nombre: "Documento AF",
                fechaEliminacion: "2025-01-02",
                eliminadoPor: "Carolina Rojas",
                creadoPor: "Eduardo Núñez",
                ubicacionOriginal: "Carpeta AF",
            },
            {
                id: 33,
                nombre: "Documento AG",
                fechaEliminacion: "2025-01-03",
                eliminadoPor: "Ricardo Sánchez",
                creadoPor: "Andrea Torres",
                ubicacionOriginal: "Carpeta AG",
            },
            {
                id: 34,
                nombre: "Documento AH",
                fechaEliminacion: "2025-01-04",
                eliminadoPor: "Susana García",
                creadoPor: "Pablo Díaz",
                ubicacionOriginal: "Carpeta AH",
            },
            {
                id: 35,
                nombre: "Documento AI",
                fechaEliminacion: "2025-01-05",
                eliminadoPor: "Alejandro López",
                creadoPor: "Rosa Martínez",
                ubicacionOriginal: "Carpeta AI",
            }
        ],
        notificado: [
            {
                id: 36,
                nombre: "Documento AJ",
                fechaEliminacion: "2025-01-06",
                eliminadoPor: "Daniel Hernández",
                creadoPor: "Miguel Morales",
                ubicacionOriginal: "Carpeta AJ",
            },
            {
                id: 37,
                nombre: "Documento AK",
                fechaEliminacion: "2025-01-07",
                eliminadoPor: "Laura Castro",
                creadoPor: "Isabel Ruiz",
                ubicacionOriginal: "Carpeta AK",
            },
            {
                id: 38,
                nombre: "Documento AL",
                fechaEliminacion: "2025-01-08",
                eliminadoPor: "Carlos Navarro",
                creadoPor: "Sergio Soto",
                ubicacionOriginal: "Carpeta AL",
            },
            {
                id: 39,
                nombre: "Documento AM",
                fechaEliminacion: "2025-01-09",
                eliminadoPor: "Elena Ramírez",
                creadoPor: "Patricia Mendoza",
                ubicacionOriginal: "Carpeta AM",
            },
            {
                id: 40,
                nombre: "Documento AN",
                fechaEliminacion: "2025-01-10",
                eliminadoPor: "Pablo Ortiz",
                creadoPor: "Marcela Vega",
                ubicacionOriginal: "Carpeta AN",
            }
        ],
        descartado: [
            {
                id: 41,
                nombre: "Documento AO",
                fechaEliminacion: "2025-01-11",
                eliminadoPor: "Jorge Rojas",
                creadoPor: "Ricardo Núñez",
                ubicacionOriginal: "Carpeta AO",
            },
            {
                id: 42,
                nombre: "Documento AP",
                fechaEliminacion: "2025-01-12",
                eliminadoPor: "Sandra Sánchez",
                creadoPor: "Julia Torres",
                ubicacionOriginal: "Carpeta AP",
            },
            {
                id: 43,
                nombre: "Documento AQ",
                fechaEliminacion: "2025-01-13",
                eliminadoPor: "Gustavo García",
                creadoPor: "Eduardo Díaz",
                ubicacionOriginal: "Carpeta AQ",
            },
            {
                id: 44,
                nombre: "Documento AR",
                fechaEliminacion: "2025-01-14",
                eliminadoPor: "Beatriz López",
                creadoPor: "Ana Martínez",
                ubicacionOriginal: "Carpeta AR",
            },
            {
                id: 45,
                nombre: "Documento AS",
                fechaEliminacion: "2025-01-15",
                eliminadoPor: "Pedro Hernández",
                creadoPor: "Luisa Morales",
                ubicacionOriginal: "Carpeta AS",
            }
        ],
        rescatado: [
            {
                id: 46,
                nombre: "Documento AT",
                fechaEliminacion: "2025-01-16",
                eliminadoPor: "José Castro",
                creadoPor: "Carlos Ruiz",
                ubicacionOriginal: "Carpeta AT",
            },
            {
                id: 47,
                nombre: "Documento AU",
                fechaEliminacion: "2025-01-17",
                eliminadoPor: "Isabel Soto",
                creadoPor: "Elena Navarro",
                ubicacionOriginal: "Carpeta AU",
            },
            {
                id: 48,
                nombre: "Documento AV",
                fechaEliminacion: "2025-01-18",
                eliminadoPor: "Sergio Ramírez",
                creadoPor: "Patricia Mendoza",
                ubicacionOriginal: "Carpeta AV",
            },
            {
                id: 49,
                nombre: "Documento AW",
                fechaEliminacion: "2025-01-19",
                eliminadoPor: "Miguel Ortiz",
                creadoPor: "Lucía Vega",
                ubicacionOriginal: "Carpeta AW",
            },
            {
                id: 50,
                nombre: "Documento AX",
                fechaEliminacion: "2025-01-20",
                eliminadoPor: "Carolina Rojas",
                creadoPor: "Eduardo Núñez",
                ubicacionOriginal: "Carpeta AX",
            },
        ]
    }
}